mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user : root
  password: zxczxc
  log-level: dev
logger:
  level: debug
  prefix: "[GIN_SERVER]"
  director: log
  show-line: true
  log-in-console : true
system:
  host: "127.0.0.1"
  port: 8080
  env: debug